import test,{beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {reset,actor,gm,player,other,setTop,ID,clone} from './harness.mjs';
const {execute,stack,enqueue,processRequest}=await import('../through-the-breach/scripts/cards.mjs');
beforeEach(()=>reset());
async function prepared(){const a=actor();await execute(gm,{op:'setupActor',actorId:a.id});return a;}
async function flip(a,extra={}){await execute(player,{op:'duel',actorId:a.id,kind:'duel',skill:'literacy',aspect:'intellect',tn:10,positive:0,negative:0,...extra});return game.messages.find(m=>m.getFlag(ID,'duel')&&!m.getFlag(ID,'duel').closed);}
test('Idempotent setup: native deck54 + twist13, private hand observers only',async()=>{const a=await prepared();await execute(gm,{op:'setupActor',actorId:a.id});assert.equal(game.cards.size,6);assert.equal(stack('fate').cards.size,54);assert.equal(stack('twist',a.id).cards.size,13);assert.deepEqual(stack('hand',a.id).ownership,{default:0,[player.id]:2});});
test('Prologue draws three from each personal deck, never the shared deck',async()=>{const a=await prepared();await execute(gm,{op:'prologue'});assert.equal(stack('hand',a.id).cards.size,3);assert.equal(stack('twist',a.id).availableCards.length,10);assert.equal(stack('fate').availableCards.length,54);});
test('Foreign actors and GM-only operations rejected',async()=>{const a=await prepared();await assert.rejects(()=>execute(other,{op:'duel',actorId:a.id,kind:'initiative'}));await assert.rejects(()=>execute(player,{op:'shuffle'}));});
test('Positive flip offers a choice then discards only unselected cards',async()=>{const a=await prepared();setTop(stack('fate'),[3,10]);const m=await flip(a,{positive:1});assert.equal(m.getFlag(ID,'duel').selected,null);assert.equal(stack('active').cards.size,2);await execute(player,{op:'pick',messageId:m.id,index:0});assert.equal(stack('active').cards.size,1);assert.equal(stack('discard').cards.size,1);await execute(player,{op:'finish',messageId:m.id});assert.equal(stack('active').cards.size,0);assert.equal(stack('discard').cards.size,2);});
test('Cheat moves from personal hand, finishes into personal discard, only once',async()=>{const a=await prepared();await execute(gm,{op:'prologue'});setTop(stack('fate'),[5]);const m=await flip(a);const card=stack('hand',a.id).cards.contents[0];await execute(player,{op:'cheat',messageId:m.id,cardId:card.id});assert.equal(stack('hand',a.id).cards.size,2);assert.equal(stack('discard').cards.size,1);assert.equal(stack('active').cards.size,1);await assert.rejects(()=>execute(player,{op:'cheat',messageId:m.id,cardId:stack('hand',a.id).cards.contents[0].id}));await execute(player,{op:'finish',messageId:m.id});assert.equal(stack('twistDiscard',a.id).cards.size,1);assert.equal(stack('active').cards.size,0);});
test('Black beats red; negatives forbid cheating even when red chosen',async()=>{const a=await prepared();await execute(gm,{op:'prologue'});setTop(stack('fate'),[14,0]);const m=await flip(a,{negative:1});assert.equal(m.getFlag(ID,'duel').cards[m.getFlag(ID,'duel').selected].value,0);await assert.rejects(()=>execute(player,{op:'cheat',messageId:m.id,cardId:stack('hand',a.id).cards.contents[0].id}));});
test('Red on negative flips is optional; red suit required before duel closes',async()=>{const a=await prepared();setTop(stack('fate'),[2,14]);const m=await flip(a,{negative:1});assert.equal(m.getFlag(ID,'duel').selected,null);await execute(player,{op:'pick',messageId:m.id,index:1});await assert.rejects(()=>execute(player,{op:'finish',messageId:m.id}));await execute(player,{op:'red',messageId:m.id,suit:'tomes'});await execute(player,{op:'finish',messageId:m.id});assert.equal(m.getFlag(ID,'duel').closed,true);});
test('Shuffle returns discard only; open card and personal hands are preserved',async()=>{const a=await prepared();await execute(gm,{op:'prologue'});setTop(stack('fate'),[5,7]);const m=await flip(a,{positive:1});await execute(player,{op:'pick',messageId:m.id,index:1});const held=stack('active').cards.contents[0].id;await execute(gm,{op:'shuffle'});assert.equal(stack('active').cards.size,1);assert.equal(stack('fate').availableCards.length,53);assert.equal(stack('fate').cards.get(held).drawn,true);assert.equal(stack('hand',a.id).cards.size,3);assert.equal(stack('hand',a.id).getFlag(ID,'credits'),1);});
test('Mid-flip exhaustion reshuffles only prior discard and grants bonus',async()=>{const a=await prepared(),deck=stack('fate');setTop(deck,[4]);await deck.pass(stack('discard'),deck.availableCards.toSorted((a,b)=>a.sort-b.sort).slice(1).map(c=>c.id));const m=await flip(a,{positive:3});assert.equal(m.getFlag(ID,'duel').cards.length,4);assert.equal(new Set(m.getFlag(ID,'duel').cards.map(c=>c.id)).size,4);assert.equal(stack('active').cards.size,m.getFlag(ID,'duel').selected===null?4:1);assert.equal(stack('hand',a.id).getFlag(ID,'credits'),1);});
test('Personal deck recycles discard and never recycles hand',async()=>{const a=await prepared();for(let i=0;i<13;i++){await execute(gm,{op:'give',actorId:a.id});await execute(player,{op:'discard',actorId:a.id,ids:stack('hand',a.id).cards.map(c=>c.id)});}assert.equal(stack('twist',a.id).availableCards.length,0);await execute(gm,{op:'give',actorId:a.id});assert.equal(stack('hand',a.id).cards.size,1);assert.equal(stack('twistDiscard',a.id).cards.size,0);assert.equal(stack('twist',a.id).availableCards.length,12);});
test('Overfull hand blocks new check until player chooses discards',async()=>{const a=await prepared();await execute(gm,{op:'prologue'});await execute(gm,{op:'prologue'});await assert.rejects(()=>flip(a));await execute(player,{op:'discard',actorId:a.id,ids:[stack('hand',a.id).cards.contents[0].id]});setTop(stack('fate'),[5]);await flip(a);});
test('End scene refresh is one-use, chosen discards, fill to three, no forced drop from five',async()=>{const a=await prepared();await execute(gm,{op:'prologue'});await assert.rejects(()=>execute(player,{op:'refresh',actorId:a.id,ids:[]}));await execute(gm,{op:'endDrama'});const ids=stack('hand',a.id).cards.contents.slice(0,2).map(c=>c.id);await execute(player,{op:'refresh',actorId:a.id,ids});assert.equal(stack('hand',a.id).cards.size,3);await assert.rejects(()=>execute(player,{op:'refresh',actorId:a.id,ids:[]}));});
test('NPC skill checks and initiative use rank without consuming Fate, damage flips consume cards',async()=>{const a=actor('Страж','npc',gm);await execute(gm,{op:'setup'});await execute(gm,{op:'duel',actorId:a.id,kind:'initiative'});assert.equal(stack('fate').availableCards.length,54);await execute(gm,{op:'duel',actorId:a.id,kind:'duel',skill:'pistol',aspect:'grace',positive:1,negative:0});const m=game.messages.find(m=>m.getFlag(ID,'duel')?.kind==='duel');assert.equal(m.getFlag(ID,'duel').base,2);await execute(gm,{op:'finish',messageId:m.id});setTop(stack('fate'),[8]);await execute(gm,{op:'duel',actorId:a.id,kind:'damage',positive:0,negative:0,track:[1,3,4]});assert.equal(stack('fate').availableCards.length,53);});
test('Synthetic token actor resolves from UUID, uses its own aspects',async()=>{const a=actor('Копия','npc',gm);a.uuid='Scene.test.Token.test.Actor.synthetic';a.system.aspects.might=4;await execute(gm,{op:'setup'});await execute(gm,{op:'duel',actorId:'not-a-world-actor',actorUuid:a.uuid,kind:'duel',skill:'melee',aspect:'might'});const d=game.messages.find(m=>m.getFlag(ID,'duel')).getFlag(ID,'duel');assert.equal(d.base,4);assert.equal(d.actorUuid,a.uuid);});
test('Serialized simultaneous requests draw distinct shared cards',async()=>{const a=await prepared(),b=actor('Борис','fated',other);setTop(stack('fate'),[5,6]);await Promise.all([enqueue(()=>flip(a)),enqueue(()=>execute(other,{op:'duel',actorId:b.id,kind:'duel',skill:'literacy',aspect:'intellect'}))]);assert.equal(stack('active').cards.size,2);const ids=game.messages.filter(m=>m.getFlag(ID,'duel')).map(m=>m.getFlag(ID,'duel').cards[0].id);assert.notEqual(ids[0],ids[1]);});
test('GM recovery closes interrupted checks and clears held cards',async()=>{const a=await prepared();const m=await flip(a,{positive:1});await execute(gm,{op:'recover',messageId:m.id});assert.equal(stack('active').cards.size,0);assert.equal(m.getFlag(ID,'duel').closed,true);});
test('Request processing captures payload, ignores repeated events and replay ledger',async()=>{const a=await prepared();const m=await foundry.documents.ChatMessage.create({flags:{[ID]:{request:{op:'give',actorId:a.id},status:'pending'}}});processRequest(m);processRequest(m);m.flags[ID].request.op='prologue';await enqueue(async()=>{});assert.equal(stack('hand',a.id).cards.size,1);assert.equal(m.getFlag(ID,'status'),'done');});
test('Shuffle credit must be taken or declined before a new check',async()=>{const a=await prepared();await execute(gm,{op:'shuffle'});await assert.rejects(()=>flip(a));await execute(player,{op:'declineCredit',actorId:a.id});setTop(stack('fate'),[5]);await flip(a);});
test('NPC rank 14 is not a red joker and needs no suit selection',async()=>{const a=actor('Мастер','npc',gm);a.system.rank=14;await execute(gm,{op:'setup'});await execute(gm,{op:'duel',actorId:a.id,kind:'duel',skill:'melee',aspect:'might'});const m=game.messages.find(m=>m.getFlag(ID,'duel'));await execute(gm,{op:'finish',messageId:m.id});assert.equal(m.getFlag(ID,'duel').closed,true);});
