import {createRequire} from 'node:module';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {ID,SKILLS,ASPECTS,GROUPS} from '../through-the-breach/scripts/rules.mjs';
import {defaultArtwork} from '../through-the-breach/scripts/item-art.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..','through-the-breach');
const require=createRequire('C:/Program Files/Foundry Virtual Tabletop/resources/app/package.json');
const {ClassicLevel}=require('classic-level');
const creation=JSON.parse(await readFile(resolve(root,'data/creation-catalog.json'),'utf8'));
const tarot=JSON.parse(await readFile(resolve(root,'data/tarot.json'),'utf8'));
const magia=JSON.parse(await readFile(resolve(root,'data/magic-catalog.json'),'utf8'));
const progression=JSON.parse(await readFile(resolve(root,'data/pursuit-progression.json'),'utf8'));
const pursuitTalents=JSON.parse(await readFile(resolve(root,'data/pursuit-talents.json'),'utf8'));
const normalize=s=>s.toLocaleLowerCase('ru').replace(/ё/g,'е').replace(/[^\p{L}\p{N}]/gu,'');
const hash=k=>createHash('sha256').update(k).digest('hex').slice(0,16);
const item=(key,name,type,system,catalog={})=>({_id:hash(key),name,type,img:defaultArtwork({name,type,system}),system,effects:[],folder:null,sort:0,ownership:{default:0},flags:{[ID]:{catalog:{key,...catalog}}}});
const packs={skills:Object.values(SKILLS).map(s=>item('skill-'+s.id,s.label,'talent',{category:'skill',skill:s.id,description:`${GROUPS[s.group]} · основной аспект: ${ASPECTS[s.aspect]}. Ранг хранится в разделе «Навыки» листа.`},{kind:'skill',skill:s.id})),stations:Object.entries(tarot).map(([key,t])=>item('station-'+key,t.station.name,'talent',{category:'station',reference:'Основная книга, стр. 82–83',description:`Навык Станции: ${SKILLS[t.station.skill].label}.\n${t.fate.station}`},{kind:'station',tarot:key,skill:t.station.skill})),pursuits:[],talents:[],equipment:[],magic:[],macros:[]};
for(const p of creation.pursuits){packs.pursuits.push(item(p.key,p.name,'talent',{category:'pursuit',description:p.description,reference:p.reference,eligibleSkills:Object.values(SKILLS).filter(s=>s.group===p.group).map(s=>s.id).join(', '),stepMax:10},{kind:'pursuit',starter:p.starter,step0:p.step0}));packs.talents.push(item(p.key+'-step0',p.step0,'talent',{category:'pursuitTalent',reference:p.reference,description:p.step0Description||`Талант шага 0 Стремления «${p.name}». Условия и особый эффект разрешаются по таблице этого Стремления в книге.`},{kind:'step0',pursuit:p.key}));}
for(const p of progression.pursuits){const pursuit=packs.pursuits.find(i=>i.flags[ID].catalog.key===p.key);pursuit.flags[ID].progression=p.progression;pursuit.flags[ID].drawRule={group:p.group,dramatic:p.drawRequiresDramatic,actor:p.drawActor,skill:p.drawSkill};
 for(const t of pursuitTalents.talents.filter(t=>t.pursuitKey===p.key)){const step0=packs.talents.find(i=>i.flags[ID].catalog.pursuit===p.key&&i.flags[ID].catalog.kind==='step0'&&normalize(i.name)===normalize(t.name));if(step0){step0.system.description=t.description;step0.system.reference=t.reference;continue;}packs.talents.push(item(t.key,t.name,'talent',{category:'pursuitTalent',description:t.description,reference:t.reference},{kind:'pursuitTalent',pursuit:p.key}));}
}
for(const t of creation.talents)packs.talents.push(item(t.key,t.name,'talent',{category:'general',description:t.description,reference:t.reference},{kind:'general',requirementsManual:true}));
const weapon=(name,skill,range,damage,price,capacity=0,reloadCost=1,special='')=>packs.equipment.push(item('weapon-'+name,name,'equipment',{category:'weapon',isWeapon:true,skill,range,damage,price,capacity,reloadCost,loaded:0,reserve:0,reference:`Основная книга, стр. ${skill==='pistol'?234:skill==='longArms'?232:skill==='heavyMelee'?227:228}`,description:special},{kind:'weapon',specialManual:!!special}));
for(const r of [['Охотничий нож','1','1/3/4',2,'Скрываемое'],['Дубина','2','2/2/4',4,'Оглушающий'],['Ручной топор','1','1/3/4',2,'Метательное'],['Джавелин','1','1/3/4',5,'Метательное; Замедляющий при броске'],['Меч','2','2/3/4',10,''],['Тонфа','1','1/3/4',3,'Оглушающий']])weapon(r[0],'melee',r[1]+' ярд.',r[2],r[3],0,1,r[4]);
for(const r of [['Штык (винтовочный)','2','1/3/4',4],['Проломный топор','2','2/3/4',18],['Привратное копьё','2','2/3/4',8],['Большой меч','2','3/4/6',22],['Древковое оружие','3','2/3/4',18],['Ж/Д Молот','2','2/4/6',6],['Посох','2','1/2/4',1]])weapon(r[0],'heavyMelee',r[1]+' ярд.',r[2],r[3],0,1,'Особые свойства сверяются по таблице оружия.');
for(const r of [['Акстон&Ко. Модель 1842',10,'2/3/4',3,1,2,''],['БиД Дерринджер Гатлинга',6,'2/3/3',20,9,2,'Взрывной выстрел, Скрываемое'],['БиД Карманный',6,'2/3/3',7,4,2,'Скрываемое'],['Заводной пистолет',12,'2/4/5',20,6,2,''],['ВМФ Колиера',12,'2/3/4',9,6,2,''],['Суровый всадник Колиера',10,'2/3/4',19,6,2,'Веерное'],['Трёхствольный Маучер',6,'2/2/5',14,3,4,'Многоствольное'],['Миротворец',10,'2/3/5',27,6,1,'Устрашающее'],['Револьвер Вольеры',10,'2/3/4',8,7,4,''],['Весхорн и Смитт #3',12,'2/3/4',19,6,1,'']])weapon(r[0],'pistol',r[1]+' ярд.',...r.slice(2));
for(const r of [['Честерфилд 1879',18,'2/3/5',14,10,3],['Молния Кольера 1902',18,'3/3/4',20,12,2],['Мушкетон Энфилда',16,'2/3/4',5,1,2],['Винтовка Хоукен',16,'2/3/5',5,1,3],['Узор Хаулза 1874',24,'3/5/6',20,1,1],['Залповое орудие Нок',12,'2/3/4',20,7,4],['Ямисака Тип 30',18,'3/4/5',22,5,2]])weapon(r[0],'longArms',r[1]+' ярд.',...r.slice(2),'Особые свойства сверяются по таблице оружия.');
for(const [name,slot,type,price] of [['Бармица','head','light',3],['Поножи','legs','light',5],['Нагрудная пластина','chest','heavy',19],['Бригантина','chest','light',7],['Рукавицы или Наручи','arms','light',5]])packs.equipment.push(item('armor-'+name,name,'equipment',{category:'armor',armorSlot:slot,armorType:type,price,reference:'Основная книга, стр. 242'},{kind:'armor'}));
for(const s of Object.values(SKILLS).filter(s=>!['magic','close','ranged'].includes(s.group)))packs.equipment.push(item('toolkit-'+s.id,`Набор: ${s.label}`,'equipment',{category:'toolkit',price:25,reference:'Основная книга, стр. 225',description:`Набор инструментов для навыка «${s.label}».`},{kind:'toolkit',skill:s.id}));
for(const [key,name,command] of [['create','Создать Сужденного','game.ttb.createCharacter()'],['prologue','Пролог — раздать три карты','game.ttb.beginSession()'],['scene','Окончание сцены','game.ttb.endScene()'],['epilogue','Эпилог — окончание сессии','game.ttb.endSession()']])packs.macros.push({_id:hash('macro-'+key),name,type:'script',scope:'global',command:`if (!game.user.isGM) ui.notifications.warn("Команда доступна мастеру."); else await ${command};`,img:"systems/through-the-breach/assets/ui/fate.svg",folder:null,sort:0,ownership:{default:0},flags:{[ID]:{catalog:{key,kind:'macro'}}}});
for(const m of magia)packs.magic.push(item(m.key,m.name,'magic',{...m.system,description:m.description+(m.variableTN?'\nСЛ переменная. Мастер рассчитывает её по описанию, вводит в запись и включает доступность.':''),reference:m.reference},{kind:'magia',variableTN:m.variableTN}));
for(const [name,tn,page,ap] of [['Дополнительная Масть',-3,272,0],['Изменение Дальности',null,272,0],['Альтернативная сопротивляемость',2,273,0],['Взрыв',2,273,0],['Род Конструкта',2,273,0],['Комбинированное заклинание',5,273,0],['Задержка',null,273,0],['Объект фокуса',null,274,0],['Усилить Импульс',2,274,0],['Повысить урон',2,274,0],['Игнорировать персонажа',2,274,0],['Увеличить ОД',-3,274,1],['Повышение сопротивляемости',2,274,0],['Неодушевленный род',3,274,0],['Увеличенная длительность',2,275,0],['Импульс',4,275,0],['Живой род',1,275,0],['Род Местности',3,275,0],['Уменьшить ОД',5,275,-1],['Уменьшить урон',-1,275,0],['Снизить сопротивление',-1,276,0],['Уменьшить тяжесть',-3,276,0],['Род нежити',2,276,0],['Тьма',1,276,0],['Разложение',1,276,0],['Электричество',3,276,0],['Огонь',3,276,0],['Лед',3,277,0],['Заражение',2,277,0],['Ужас',1,277,0],['Свет',1,277,0],['Природа',2,277,0],['Ветер',1,277,0],['Яд',1,277,0],['Дух',3,277,0],['Вода',1,277,0]])packs.magic.push(item('immuto-'+name,name,'magic',{magicKind:'immuto',tnAdjustment:tn??0,apAdjustment:ap,maxCopies:1,equipped:tn!==null,reference:`Основная книга, стр. ${page}`,description:`Мастер проверяет условия, совместимость, эффект и допустимое число повторений по указанной странице.\n${tn===null?'Поправка зависит от выбора: перед использованием задайте СЛ и включите доступность.':'Поправка СЛ: '+tn}.\nДополнительная Масть требует добавить обязательную масть к Магии вручную; альтернативное сопротивление меняет поле сопротивления Магии. Эти эффекты не применяются одной числовой поправкой.`},{kind:'immuto',configurationRequired:true}));
const labels={skills:'Навыки',stations:'Станции Таро',pursuits:'Базовые Стремления',talents:'Таланты',equipment:'Снаряжение',magic:'Магии и Иммуто',macros:'Команды мастера'};
for(const docs of Object.values(packs))for(const d of docs)d._stats={coreVersion:'14.365',systemId:ID,systemVersion:'0.5.4',createdTime:0,modifiedTime:0,lastModifiedBy:null};
for(const [name,docs] of Object.entries(packs)){
 const path=resolve(root,'packs',name);await mkdir(path,{recursive:true});
 const db=new ClassicLevel(path,{keyEncoding:'utf8',valueEncoding:'json'});await db.open();await db.clear();
 const sub=db.sublevel(name==='macros'?'macros':'items',{keyEncoding:'utf8',valueEncoding:'json'});
 await sub.batch(docs.map(d=>({type:'put',key:d._id,value:d})));await db.close();
 console.log(name,docs.length);
}
await writeFile(resolve(root,'data/pack-sources.json'),JSON.stringify(packs,null,2)+'\n');
const manifestPath=resolve(root,'system.json');const manifest=JSON.parse(await readFile(manifestPath,'utf8'));
manifest.packs=Object.keys(packs).map(name=>({name,label:labels[name],path:`packs/${name}`,type:name==='macros'?'Macro':'Item',system:ID,ownership:{PLAYER:'OBSERVER',ASSISTANT:'OWNER'}}));
await writeFile(manifestPath,JSON.stringify(manifest,null,2)+'\n');
