"""Merge reviewed translations and generate immutable display baselines. No world writes."""
import json,pathlib
root=pathlib.Path(__file__).resolve().parent.parent
system=root/'through-the-breach'
def load(path):return json.loads(path.read_text(encoding='utf8'))
def save(path,obj):path.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
sourceFile=system/'lang/source.json'
source=load(sourceFile) if sourceFile.exists() else {k:{'ru':value} for k,value in load(system/'lang/ru.json')['TTB']['Text'].items()}
translated=dict(load(system/'lang/en.json')['TTB']['Text'])
for file in ['ui-translations.json','data-translations.json','root-translations.json']:
    path=root/'output/localization'/file
    if path.exists():translated.update(load(path))
ru=load(system/'lang/ru.json');ru['TTB']['Text']={k:v['ru'] for k,v in source.items()}
en=load(system/'lang/en.json');en['TTB']['Text']=translated
save(system/'lang/ru.json',ru);save(system/'lang/en.json',en)
def fingerprint(value):
    h=2166136261
    b=str(value or '').encode('utf-16-le')
    for i in range(0,len(b),2):h=((h^(b[i]|b[i+1]<<8))*16777619)&0xffffffff
    return f'{h:08x}'
names={};baselines={}
def record(key,data):
    names[key]=data['name']
    fields={'name':fingerprint(data['name'])}
    for field in ['description','reference','range','notes','characteristics']:
        if field in data.get('system',{}):fields['system.'+field]=fingerprint(data['system'][field])
    baselines[key]=fields
for docs in load(system/'data/pack-sources.json').values():
    for d in docs:record(d['flags']['through-the-breach']['catalog']['key'],d)
for entry in load(system/'data/bestiary.json')['entries']:
    record(entry['key'],entry['data'])
    for i,d in enumerate(entry['data'].get('items',[])):
        # Embedded bestiary Items inherit localization identity without modifying their rule data.
        record(entry['key']+'/item/'+str(i),d)
adventure=load(system/'data/starter-adventure.json')
for group in ['actors','journals','scenes']:
    for e in adventure[group]:
        record(e['key'],e['data'])
        record({'actors':'actor','journals':'journal','scenes':'scene'}[group]+':'+e['key'],e['data'])
        for i,d in enumerate(e['data'].get('items',[])):record(e['key']+'/item/'+str(i),d)
        for i,page in enumerate(e['data'].get('pages',[])):
            baselines[e['key']+'/page/'+str(i)]={'name':fingerprint(page['name']),'text.content':fingerprint(page.get('text',{}).get('content',''))}
save(system/'lang/document-names.json',names);save(system/'lang/document-baselines.json',baselines)
generated='// Generated by tools/build-localization.py. Canonical display baselines, no mechanical rules.\n'
for name,data in [('SOURCE',ru['TTB']['Text']),('NAMES',names),('BASELINES',baselines)]:
    generated+='export const '+name+'='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n'
(system/'scripts/localization-data.mjs').write_text(generated,encoding='utf8')
missing=[k for k in source if not translated.get(k)]
print(f'English coverage: {len(source)-len(missing)}/{len(source)}; missing: {len(missing)}')
save(root/'output/localization/missing.json',{k:source[k] for k in missing})
